fullnameOverride: cert-manager

resources:
  requests:
    cpu: 10m
    memory: 32Mi

ingressShim:
  issuerName: letsencrypt-staging
  requireAnnotations: false
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

webhook:
  enabled: true
